### ISSUE TITLE
How to make a Pull Request with Visual Studio Code ?

### ISSUE THREAD

**Issue by chrapati24** [SPinti-Software/CpcdosOS2.1#7]
Hello,

So I want make PR to contribute. But, I can't make this since Visual Studio Code with the extension. Can you help me please ?

**Comment by d0p1s4m4** [comment]
short: You can't

Well, maybe with a third party plugin.
VSCode has an integrated git "client" (git != github) , but pull request are github feature and not related to git itself.

In order to make a pull request you need to push your change in your own repo (or branch) and then in the github web interface you can make a pull request. (here is a doc: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request)

You should also read: https://guides.github.com/
